version: "3.3"

services:

  traefik:
    image: "traefik:v2.8"
    container_name: ${APP_NAME:?docker-server}-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
    ports:
      # Web
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_ROOT}/config/traefik/static.yml:/etc/traefik/traefik.yml:ro
      - ${APP_ROOT}/config/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ${APP_ROOT}/certs/acme.json:/acme.json
      - ${APP_ROOT}/data/traefik/access.log:/logs/access.log
    networks:
      - proxy

  whoami:
    image: "traefik/whoami:v1.8.1"
    container_name: ${APP_NAME:?docker-server}-whoami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST_NAME}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      # If port is different than 80, use the following service:
      # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
    networks:
      - proxy
    depends_on:
      - traefik

  portainer:
    image: portainer/portainer-ce:2.13.1-alpine
    container_name: ${APP_NAME:?docker-server}-portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - proxy
    depends_on:
      - traefik

  filebrowser:
    image: filebrowser/filebrowser:v2.22.1
    container_name: ${APP_NAME:?docker-server}-filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${UID}:${GID}"
    volumes:
      - ${FILEBROWSER_ROOT}:/srv
      - ${APP_ROOT}/data/filebrowser/filebrowser.db:/database.db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_HOST_NAME}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - proxy
    depends_on:
      - traefik

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: ${APP_NAME:?docker-server}-autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5 # check every 5 seconds
      - AUTOHEAL_START_PERIOD=0 # wait 0 seconds before first health check
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10 # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      - DOCKER_SOCK=/var/run/docker.sock # Unix socket for curl requests to Docker API
      - CURL_TIMEOUT=30 # --max-time seconds for curl requests to Docker API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dozzle:
    image: amir20/dozzle:v3.12.6
    container_name: ${APP_NAME:?docker-server}-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle.rule=Host(`${DOZZLE_HOST_NAME}`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.service=dozzle"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: ${APP_NAME:?docker-server}-watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_HOOK_URL}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${SLACK_IDENTIFIER}
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=${SLACK_CHANNEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

  duplicati:
    image: linuxserver/duplicati:2.0.6
    container_name: ${APP_NAME:?docker-server}-duplicati
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - CLI_ARGS= #optional
    volumes:
      - ${APP_ROOT}/config/duplicati:/config
      - ${APP_ROOT}/backups:/backups
      - ${SOURCE_PATH}:/sources:ro
      - ${VOLUME_PATH}:/volume-sources-:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.duplicati.rule=Host(`${DUPLICATI_HOST_NAME}`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.routers.duplicati.tls.certresolver=myresolver"
      - "traefik.http.routers.duplicati.service=duplicati"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
    networks:
      - proxy

volumes:
  portainer_data:
    name: portainer-data

networks:
  proxy:
    external: true
