http:
  routers:
    traefik:
      service: "api@internal"
      rule: "Host(`traefik.ritthikrai.com`)"
  middlewares:
    secureHeaders:
      redirectScheme:
        scheme: https
        permanent: true
