http:
  routers:
    traefik:
      service: "api@internal"
      middlewares:
        - "simpleAuth"
      rule: "Host(`traefik.docker.localhost`)"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "domain.local"
            sans:
              - "*.domain.local"
  middlewares:
    secureHeaders:
      redirectScheme:
        scheme: https
        permanent: true
    simpleAuth:
      basicAuth:
        removeHeader: true
        users:
          - "admin:$2y$05$4PEg4oTrAfA1UcLY59u6luQ.GmAt2O1DArx6GPqvD1BXDBIfiIuYy"

tls:
  certificates:
    - certFile: "/etc/cert/certificate.pem"
      keyFile: "/etc/cert/private.pem"
