global:
  sendAnonymousUsage: false

accessLog:
  filePath: "/logs/access.log"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls: {}
    
